//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhiPhuongTien
    {
        public int Ma { get; set; }
        public string Ten { get; set; }
        public int MaPhuongTien { get; set; }
        public Nullable<int> ThoiGian { get; set; }
        public Nullable<int> TienPhi { get; set; }
        public string MieuTa { get; set; }
    
        public virtual PhuongTien PhuongTien { get; set; }
    }
}
