//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBanBuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBanBuon()
        {
            this.ChiTietHoaDonBanBuon = new HashSet<ChiTietHoaDonBanBuon>();
            this.PhuongTienDiGiaoHang = new HashSet<PhuongTienDiGiaoHang>();
        }
    
        public int Ma { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<int> ThoiGian { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> ThanhToan { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonBanBuon> ChiTietHoaDonBanBuon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuongTienDiGiaoHang> PhuongTienDiGiaoHang { get; set; }
    }
}
