//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonGiaKhachHang = new HashSet<DonGiaKhachHang>();
            this.HoaDonBanBuon = new HashSet<HoaDonBanBuon>();
            this.KhachHangNoVo = new HashSet<KhachHangNoVo>();
            this.LichSuKhachHangTraNoTien = new HashSet<LichSuKhachHangTraNoTien>();
            this.NhomKhachHang = new HashSet<NhomKhachHang>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string TenChuCuaHang { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> KhoangCach { get; set; }
        public string GhiChuDauTu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<byte> KichHoat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonGiaKhachHang> DonGiaKhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBanBuon> HoaDonBanBuon { get; set; }
        public virtual KhachHangNoTien KhachHangNoTien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHangNoVo> KhachHangNoVo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuKhachHangTraNoTien> LichSuKhachHangTraNoTien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomKhachHang> NhomKhachHang { get; set; }
    }
}
