//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuKhachHangTraNoTien
    {
        public int Ma { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<int> ThoiGian { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
