//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongTien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhuongTien()
        {
            this.ChiPhiPhuongTien = new HashSet<ChiPhiPhuongTien>();
            this.PhuongTienDiGiaoHang = new HashSet<PhuongTienDiGiaoHang>();
            this.PhuongTienDiNhapHang = new HashSet<PhuongTienDiNhapHang>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string BienSo { get; set; }
        public Nullable<int> TaiTrong { get; set; }
        public string MieuTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<byte> Loai { get; set; }
        public Nullable<byte> KichHoat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhiPhuongTien> ChiPhiPhuongTien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuongTienDiGiaoHang> PhuongTienDiGiaoHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuongTienDiNhapHang> PhuongTienDiNhapHang { get; set; }
    }
}
