//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDonBanBuon = new HashSet<ChiTietHoaDonBanBuon>();
            this.ChiTietNhapHang = new HashSet<ChiTietNhapHang>();
            this.CuocVoCongTy = new HashSet<CuocVoCongTy>();
            this.DonGiaKhachHang = new HashSet<DonGiaKhachHang>();
            this.HoaDonBanLe = new HashSet<HoaDonBanLe>();
            this.KhachHangNoVo = new HashSet<KhachHangNoVo>();
            this.SanPhamDoiDoiTra = new HashSet<SanPhamDoiDoiTra>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public Nullable<int> SoLuongSanPham { get; set; }
        public Nullable<int> SoLuongVo { get; set; }
        public Nullable<double> DungTich { get; set; }
        public string MieuTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<byte> Loai { get; set; }
        public Nullable<byte> KichHoat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonBanBuon> ChiTietHoaDonBanBuon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapHang> ChiTietNhapHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuocVoCongTy> CuocVoCongTy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonGiaKhachHang> DonGiaKhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBanLe> HoaDonBanLe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHangNoVo> KhachHangNoVo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamDoiDoiTra> SanPhamDoiDoiTra { get; set; }
    }
}
