//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamDoiDoiTra
    {
        public int Ma { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThoiGianDemDi { get; set; }
        public Nullable<int> ThoiGianNhanLai { get; set; }
        public Nullable<byte> TrangThai { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
